---
# tasks file for devapp
- name: Install apache 
  yum: name=httpd state=present 

- name: Start Apache service
  service: name=httpd state=started enabled=yes
  

    #- name: File template for the app
    #  template: src=index.html_old.j2 dest=/var/www/html/index.html_old
    #  notify: restart apache

- name: Copy files to servers
  copy: src=app.txt dest=/home/jenkins owner=jenkins group=jenkins mode=0775

- name: Copy html file containing index file
  copy: src=html/ dest=/var/www/html/

- include: modify_test.yml

