---
# tasks file for devapp
- name: Install apache servera
  become: true
  become_user: root
  yum: name=httpd state=present 

- name: Start Apache servera
  become: true
  become_user: root
  service: name=httpd state=started enabled=yes
  

- name: File template for the app
  template: src=index.html_old.j2 dest=/var/www/html/index.html_old
  notify: restart apache

- name: Copy files to servers
  copy: src=app.txt dest=/home/jenkins owner=jenkins group=jenkins mode=0775

- name: Remove html directory 
  file: path=/var/www/html state=absent 

- name: Copy html file containing index file
  copy: src=html/ dest=/var/www/ owner=jenkins group=jenkins mode=0775

- include: modify_test.yml

